use anyhow::{Context, Result, bail};
use std::path::Path;

use super::report::Report;

// `Clone` is required by `services()`, which `concat`s the split data slices
// into one matrix; the fields are all `Copy` references, so this is cheap.
#[derive(Clone)]
pub(crate) struct ServiceCoverage<'a> {
    name: &'a str,
    rows: &'a [EndpointCoverage<'a>],
}

#[cfg(test)]
impl<'a> ServiceCoverage<'a> {
    pub(crate) const fn new(name: &'a str, rows: &'a [EndpointCoverage<'a>]) -> Self {
        Self { name, rows }
    }
}

pub(crate) struct EndpointCoverage<'a> {
    endpoint: &'a str,
    implementation: &'a str,
    checks: &'a [&'a str],
}

#[cfg(test)]
impl<'a> EndpointCoverage<'a> {
    pub(crate) const fn new(
        endpoint: &'a str,
        implementation: &'a str,
        checks: &'a [&'a str],
    ) -> Self {
        Self {
            endpoint,
            implementation,
            checks,
        }
    }
}

pub fn write_markdown(path: &Path, report: &Report, report_path: &str) -> Result<()> {
    let out = render_markdown(report, report_path);
    atomic_write(path, &out)
}

/// Regenerate the coverage doc from an existing report file, without re-running
/// the (slow, network-bound) live suites. Lets `--coverage-write` refresh the doc
/// deterministically after a coverage-map edit, so the doc never depends on a
/// fully-green live run that a slow upstream could abort.
pub fn write_markdown_from_file(doc_path: &Path, report_path: &Path) -> Result<()> {
    let report = Report::read_json(report_path)?;
    write_markdown(doc_path, &report, &report_path.display().to_string())
}

pub fn check_markdown(doc_path: &Path, report_path: &Path) -> Result<()> {
    check_markdown_for_rows(doc_path, report_path, &services())
}

pub(crate) fn check_markdown_for_rows(
    doc_path: &Path,
    report_path: &Path,
    services: &[ServiceCoverage<'_>],
) -> Result<()> {
    let report = Report::read_json(report_path)?;
    let expected = render_markdown_for_rows(&report, &report_path.display().to_string(), services);
    let actual = std::fs::read_to_string(doc_path)
        .with_context(|| format!("failed to read {}", doc_path.display()))?;

    if actual != expected {
        bail!(
            "{} is stale; run `cargo xtask live --suite all` to regenerate it",
            doc_path.display()
        );
    }

    Ok(())
}

pub fn render_markdown(report: &Report, report_path: &str) -> String {
    render_markdown_for_rows(report, report_path, &services())
}

pub(crate) fn render_markdown_for_rows(
    report: &Report,
    report_path: &str,
    services: &[ServiceCoverage<'_>],
) -> String {
    let total = report.len();
    let passed = report.passed_count();
    let failed = total.saturating_sub(passed);
    let mut out = String::new();

    out.push_str("# Yarr Live Endpoint Coverage\n\n");
    out.push_str("Generated by `cargo xtask live`.\n\n");
    out.push_str(&format!(
        "Result: {total} live checks recorded in `{report_path}`; {passed} passed, {failed} failed.\n\n"
    ));
    out.push_str("Scope note: the \"service API endpoint\" column lists the endpoint families Yarr allowlists and the concrete upstream endpoints Yarr's curated actions use. It is not a complete inventory of every endpoint exposed by the upstream products.\n\n");

    for service in services {
        out.push_str(&format!("## {}\n\n", service.name));
        out.push_str("| Service API endpoint | Yarr implementation | Live test |\n");
        out.push_str("|---|---|---|\n");
        for row in service.rows {
            out.push_str(&format!(
                "| `{}` | {} | {} |\n",
                escape_cell(row.endpoint),
                escape_cell(row.implementation),
                row_status(report, row.checks)
            ));
        }
        out.push('\n');
    }

    out
}

fn atomic_write(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }

    let tmp_path = path.with_file_name(format!(
        ".{}.tmp",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("LIVE_ENDPOINT_COVERAGE.md")
    ));
    std::fs::write(&tmp_path, contents)
        .with_context(|| format!("failed to write {}", tmp_path.display()))?;
    std::fs::rename(&tmp_path, path).with_context(|| {
        format!(
            "failed to move {} into {}",
            tmp_path.display(),
            path.display()
        )
    })
}

fn row_status(report: &Report, checks: &[&str]) -> String {
    if checks.is_empty() {
        return "Not covered by current shart live matrix".to_owned();
    }

    let missing = checks
        .iter()
        .filter(|check| report.check_passed(check).is_none())
        .map(|check| format!("`{check}`"))
        .collect::<Vec<_>>();
    if !missing.is_empty() {
        return format!("Missing check: {}", missing.join(", "));
    }

    if checks
        .iter()
        .all(|check| report.check_passed(check) == Some(true))
    {
        "Pass".to_owned()
    } else {
        "Fail".to_owned()
    }
}

fn escape_cell(value: &str) -> String {
    value.replace('|', "\\|")
}

mod services_part1;
mod services_part2;

/// The full live-coverage service matrix, assembled from the split data modules.
///
/// The data table is large enough that it is kept in two sibling modules
/// ([`services_part1`]/[`services_part2`]) to stay under the workspace
/// module-size limit; this re-joins them into one slice for the renderer.
fn services() -> Vec<ServiceCoverage<'static>> {
    [services_part1::SERVICES, services_part2::SERVICES].concat()
}
