use anyhow::{Context, Result, bail};
use std::path::Path;

use super::report::Report;

pub(crate) struct ServiceCoverage<'a> {
    name: &'a str,
    rows: &'a [EndpointCoverage<'a>],
}

#[cfg(test)]
impl<'a> ServiceCoverage<'a> {
    pub(crate) const fn new(name: &'a str, rows: &'a [EndpointCoverage<'a>]) -> Self {
        Self { name, rows }
    }
}

pub(crate) struct EndpointCoverage<'a> {
    endpoint: &'a str,
    implementation: &'a str,
    checks: &'a [&'a str],
}

#[cfg(test)]
impl<'a> EndpointCoverage<'a> {
    pub(crate) const fn new(
        endpoint: &'a str,
        implementation: &'a str,
        checks: &'a [&'a str],
    ) -> Self {
        Self {
            endpoint,
            implementation,
            checks,
        }
    }
}

pub fn write_markdown(path: &Path, report: &Report, report_path: &str) -> Result<()> {
    let out = render_markdown(report, report_path);
    atomic_write(path, &out)
}

pub fn check_markdown(doc_path: &Path, report_path: &Path) -> Result<()> {
    check_markdown_for_rows(doc_path, report_path, SERVICES)
}

pub(crate) fn check_markdown_for_rows(
    doc_path: &Path,
    report_path: &Path,
    services: &[ServiceCoverage<'_>],
) -> Result<()> {
    let report = Report::read_json(report_path)?;
    let expected = render_markdown_for_rows(&report, &report_path.display().to_string(), services);
    let actual = std::fs::read_to_string(doc_path)
        .with_context(|| format!("failed to read {}", doc_path.display()))?;

    if actual != expected {
        bail!(
            "{} is stale; run `cargo xtask live --suite all` to regenerate it",
            doc_path.display()
        );
    }

    Ok(())
}

pub fn render_markdown(report: &Report, report_path: &str) -> String {
    render_markdown_for_rows(report, report_path, SERVICES)
}

pub(crate) fn render_markdown_for_rows(
    report: &Report,
    report_path: &str,
    services: &[ServiceCoverage<'_>],
) -> String {
    let total = report.len();
    let passed = report.passed_count();
    let failed = total.saturating_sub(passed);
    let mut out = String::new();

    out.push_str("# Rustarr Live Endpoint Coverage\n\n");
    out.push_str("Generated by `cargo xtask live`.\n\n");
    out.push_str(&format!(
        "Result: {total} live checks recorded in `{report_path}`; {passed} passed, {failed} failed.\n\n"
    ));
    out.push_str("Scope note: the \"service API endpoint\" column lists the endpoint families Rustarr allowlists and the concrete upstream endpoints Rustarr's curated actions use. It is not a complete inventory of every endpoint exposed by the upstream products.\n\n");

    for service in services {
        out.push_str(&format!("## {}\n\n", service.name));
        out.push_str("| Service API endpoint | Rustarr implementation | Live test |\n");
        out.push_str("|---|---|---|\n");
        for row in service.rows {
            out.push_str(&format!(
                "| `{}` | {} | {} |\n",
                escape_cell(row.endpoint),
                escape_cell(row.implementation),
                row_status(report, row.checks)
            ));
        }
        out.push('\n');
    }

    out
}

fn atomic_write(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }

    let tmp_path = path.with_file_name(format!(
        ".{}.tmp",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("LIVE_ENDPOINT_COVERAGE.md")
    ));
    std::fs::write(&tmp_path, contents)
        .with_context(|| format!("failed to write {}", tmp_path.display()))?;
    std::fs::rename(&tmp_path, path).with_context(|| {
        format!(
            "failed to move {} into {}",
            tmp_path.display(),
            path.display()
        )
    })
}

fn row_status(report: &Report, checks: &[&str]) -> String {
    if checks.is_empty() {
        return "Not covered by current shart live matrix".to_owned();
    }

    let missing = checks
        .iter()
        .filter(|check| report.check_passed(check).is_none())
        .map(|check| format!("`{check}`"))
        .collect::<Vec<_>>();
    if !missing.is_empty() {
        return format!("Missing check: {}", missing.join(", "));
    }

    if checks
        .iter()
        .all(|check| report.check_passed(check) == Some(true))
    {
        "Pass".to_owned()
    } else {
        "Fail".to_owned()
    }
}

fn escape_cell(value: &str) -> String {
    value.replace('|', "\\|")
}

const SERVICES: &[ServiceCoverage] = &[
    ServiceCoverage {
        name: "Sonarr",
        rows: &[
            EndpointCoverage {
                endpoint: "/api/v3/system/status",
                implementation: "`service_status`; generic `api_get`; generic `api_post` confirm guard and confirmed upstream-error probe",
                checks: &[
                    "cli status sonarr",
                    "api_get sonarr /api/v3/system/status",
                    "api_post blocked sonarr",
                    "api_post confirmed upstream error sonarr",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v3/qualityprofile",
                implementation: "`quality_profiles`; also used by `set_quality` and `add`",
                checks: &[
                    "mcporter sonarr quality_profiles",
                    "mcporter confirmed arr item lifecycle sonarr",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v3/series",
                implementation: "`list`; also used by `set_quality`, `monitor`, `unmonitor`, and selection flows",
                checks: &[
                    "mcporter sonarr list",
                    "mcporter confirmed arr item lifecycle sonarr",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v3/wanted/missing?pageSize=50",
                implementation: "`wanted`",
                checks: &["mcporter sonarr wanted"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/queue?pageSize=50",
                implementation: "`queue`",
                checks: &["mcporter sonarr queue"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/history?pageSize=50",
                implementation: "`history`",
                checks: &["mcporter sonarr history"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/rootfolder",
                implementation: "`rootfolders`; also used by `add` setup/validation",
                checks: &[
                    "mcporter sonarr rootfolders",
                    "mcporter confirmed arr item lifecycle sonarr",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v3/health",
                implementation: "`health`",
                checks: &["mcporter sonarr health"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/series/editor",
                implementation: "`set_quality`, `monitor`, `unmonitor`",
                checks: &["mcporter confirmed arr item lifecycle sonarr"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/command",
                implementation: "`search`, `refresh`",
                checks: &["mcporter confirmed arr item lifecycle sonarr"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/series/lookup?term=...",
                implementation: "`add`",
                checks: &["mcporter confirmed arr item lifecycle sonarr"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/series POST",
                implementation: "`add`",
                checks: &["mcporter confirmed arr item lifecycle sonarr"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/series/{id}?deleteFiles={true|false} DELETE",
                implementation: "`delete`",
                checks: &["mcporter confirmed arr item lifecycle sonarr"],
            },
            EndpointCoverage {
                endpoint: "/api/v3 allowlist",
                implementation: "generic `api_get`, `api_post`, `api_put`, `api_delete`",
                checks: &[
                    "mcporter confirmed generic error sonarr api_post",
                    "mcporter confirmed generic error sonarr api_put",
                    "mcporter confirmed generic error sonarr api_delete",
                ],
            },
        ],
    },
    ServiceCoverage {
        name: "Radarr",
        rows: &[
            EndpointCoverage {
                endpoint: "/api/v3/system/status",
                implementation: "`service_status`; generic `api_get`; generic `api_post` confirm guard and confirmed upstream-error probe",
                checks: &[
                    "cli status radarr",
                    "api_get radarr /api/v3/system/status",
                    "api_post blocked radarr",
                    "api_post confirmed upstream error radarr",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v3/qualityprofile",
                implementation: "`quality_profiles`; also used by `set_quality` and `add`",
                checks: &[
                    "mcporter radarr quality_profiles",
                    "mcporter confirmed arr item lifecycle radarr",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v3/movie",
                implementation: "`list`; also used by `set_quality`, `monitor`, `unmonitor`, and selection flows",
                checks: &[
                    "mcporter radarr list",
                    "mcporter confirmed arr item lifecycle radarr",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v3/wanted/missing?pageSize=50",
                implementation: "`wanted`",
                checks: &["mcporter radarr wanted"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/queue?pageSize=50",
                implementation: "`queue`",
                checks: &["mcporter radarr queue"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/history?pageSize=50",
                implementation: "`history`",
                checks: &["mcporter radarr history"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/rootfolder",
                implementation: "`rootfolders`; also used by `add` setup/validation",
                checks: &[
                    "mcporter radarr rootfolders",
                    "mcporter confirmed arr item lifecycle radarr",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v3/health",
                implementation: "`health`",
                checks: &["mcporter radarr health"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/movie/editor",
                implementation: "`set_quality`, `monitor`, `unmonitor`",
                checks: &["mcporter confirmed arr item lifecycle radarr"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/command",
                implementation: "`search`, `refresh`",
                checks: &["mcporter confirmed arr item lifecycle radarr"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/movie/lookup?term=...",
                implementation: "`add`",
                checks: &["mcporter confirmed arr item lifecycle radarr"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/movie POST",
                implementation: "`add`",
                checks: &["mcporter confirmed arr item lifecycle radarr"],
            },
            EndpointCoverage {
                endpoint: "/api/v3/movie/{id}?deleteFiles={true|false} DELETE",
                implementation: "`delete`",
                checks: &["mcporter confirmed arr item lifecycle radarr"],
            },
            EndpointCoverage {
                endpoint: "/api/v3 allowlist",
                implementation: "generic `api_get`, `api_post`, `api_put`, `api_delete`",
                checks: &[
                    "mcporter confirmed generic error radarr api_post",
                    "mcporter confirmed generic error radarr api_put",
                    "mcporter confirmed generic error radarr api_delete",
                ],
            },
        ],
    },
    ServiceCoverage {
        name: "Prowlarr",
        rows: &[
            EndpointCoverage {
                endpoint: "/api/v1/system/status",
                implementation: "`service_status`; generic `api_get`; generic `api_post` confirm guard and confirmed upstream-error probe",
                checks: &[
                    "cli status prowlarr",
                    "api_get prowlarr /api/v1/system/status",
                    "api_post blocked prowlarr",
                    "api_post confirmed upstream error prowlarr",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v1/indexer",
                implementation: "`indexers`; one-indexer lookup for `indexer_test`; generic `api_get`",
                checks: &[
                    "mcporter prowlarr indexers",
                    "api_get prowlarr /api/v1/indexer",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v1/search?query=...&type=search&limit=100[&indexerIds=...]",
                implementation: "`indexer_search`",
                checks: &["mcporter prowlarr indexer_search"],
            },
            EndpointCoverage {
                endpoint: "/api/v1/indexerstats",
                implementation: "`indexer_stats`",
                checks: &["mcporter prowlarr indexer_stats"],
            },
            EndpointCoverage {
                endpoint: "/api/v1/indexer/testall",
                implementation: "`indexer_test` for all indexers",
                checks: &["mcporter confirmed write prowlarr indexer_test"],
            },
            EndpointCoverage {
                endpoint: "/api/v1/indexer/test",
                implementation: "`indexer_test` for one indexer",
                checks: &["mcporter prowlarr indexer_test"],
            },
            EndpointCoverage {
                endpoint: "/api/v1/tag",
                implementation: "confirmed generic tag lifecycle through `api_post`, `api_put`, `api_delete`",
                checks: &["mcporter confirmed write lifecycle prowlarr tag"],
            },
            EndpointCoverage {
                endpoint: "/api/v1 allowlist",
                implementation: "generic `api_get`, `api_post`, `api_put`, `api_delete`",
                checks: &[
                    "mcporter confirmed generic error prowlarr api_post",
                    "mcporter confirmed generic error prowlarr api_put",
                    "mcporter confirmed generic error prowlarr api_delete",
                ],
            },
        ],
    },
    ServiceCoverage {
        name: "Tautulli",
        rows: &[
            EndpointCoverage {
                endpoint: "/api/v2?cmd=get_server_info",
                implementation: "`service_status`; generic `api_get`; generic `api_post` confirm guard and confirmed upstream-error probe",
                checks: &[
                    "cli status tautulli",
                    "api_get tautulli /api/v2?cmd=get_server_info",
                    "api_post blocked tautulli",
                    "api_post confirmed upstream error tautulli",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v2?cmd=get_activity",
                implementation: "`stats_activity`",
                checks: &["mcporter tautulli stats_activity"],
            },
            EndpointCoverage {
                endpoint: "/api/v2?cmd=get_history[&start=&length=&user=]",
                implementation: "`stats_history`",
                checks: &["mcporter tautulli stats_history"],
            },
            EndpointCoverage {
                endpoint: "/api/v2?cmd=get_users",
                implementation: "`stats_users`",
                checks: &["mcporter tautulli stats_users"],
            },
            EndpointCoverage {
                endpoint: "/api/v2?cmd=get_library_names",
                implementation: "`stats_libraries`",
                checks: &["mcporter tautulli stats_libraries"],
            },
            EndpointCoverage {
                endpoint: "/api/v2?cmd=refresh_libraries_list",
                implementation: "`stats_refresh_libraries`",
                checks: &["mcporter confirmed write tautulli maintenance lifecycle"],
            },
            EndpointCoverage {
                endpoint: "/api/v2?cmd=refresh_users_list",
                implementation: "`stats_refresh_users`",
                checks: &["mcporter confirmed write tautulli maintenance lifecycle"],
            },
            EndpointCoverage {
                endpoint: "/api/v2?cmd=delete_image_cache",
                implementation: "`stats_delete_image_cache`",
                checks: &["mcporter confirmed write tautulli maintenance lifecycle"],
            },
            EndpointCoverage {
                endpoint: "/api and /api/v2 allowlist",
                implementation: "generic `api_get`, `api_post`, `api_put`, `api_delete`",
                checks: &[
                    "mcporter confirmed generic error tautulli api_post",
                    "mcporter confirmed generic error tautulli api_put",
                    "mcporter confirmed generic error tautulli api_delete",
                ],
            },
        ],
    },
    ServiceCoverage {
        name: "Overseerr",
        rows: &[
            EndpointCoverage {
                endpoint: "/api/v1/status",
                implementation: "`service_status`; generic `api_get`; generic `api_post` confirm guard and confirmed upstream-error probe",
                checks: &[
                    "cli status overseerr",
                    "api_get overseerr /api/v1/status",
                    "api_post blocked overseerr",
                    "api_post confirmed upstream error overseerr",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v1/request[?filter=&take=&skip=]",
                implementation: "`requests`",
                checks: &["mcporter overseerr requests"],
            },
            EndpointCoverage {
                endpoint: "/api/v1/request POST",
                implementation: "`request_create`",
                checks: &["mcporter confirmed write overseerr request lifecycle"],
            },
            EndpointCoverage {
                endpoint: "/api/v1/request/{id}/approve",
                implementation: "`request_approve`",
                checks: &["mcporter confirmed write overseerr request lifecycle"],
            },
            EndpointCoverage {
                endpoint: "/api/v1/request/{id}/decline",
                implementation: "`request_decline`",
                checks: &["mcporter confirmed write overseerr request lifecycle"],
            },
            EndpointCoverage {
                endpoint: "/api/v1/search?query=...",
                implementation: "`request_search`",
                checks: &["mcporter overseerr request_search"],
            },
            EndpointCoverage {
                endpoint: "/api/v1 allowlist",
                implementation: "generic `api_get`, `api_post`, `api_put`, `api_delete`",
                checks: &[
                    "mcporter confirmed generic error overseerr api_post",
                    "mcporter confirmed generic error overseerr api_put",
                    "mcporter confirmed generic error overseerr api_delete",
                ],
            },
        ],
    },
    ServiceCoverage {
        name: "Bazarr",
        rows: &[
            EndpointCoverage {
                endpoint: "/api/system/status",
                implementation: "`service_status`; generic `api_get`; generic `api_post` confirm guard and confirmed upstream-error probe",
                checks: &[
                    "cli status bazarr",
                    "api_get bazarr /api/system/status",
                    "api_post blocked bazarr",
                    "api_post confirmed upstream error bazarr",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/system/health",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/system/jobs",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/system/tasks",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/movies",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/series",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/movies/subtitles",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/episodes/subtitles",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/subtitles",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/movies/wanted",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/episodes/wanted",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/movies/history",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/episodes/history",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/movies/blacklist",
                implementation: "seeded generic `api_delete` blacklist lifecycle",
                checks: &["mcporter confirmed write bazarr blacklist delete"],
            },
            EndpointCoverage {
                endpoint: "/api/episodes/blacklist",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/providers",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/plex/oauth/pin",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/plex/oauth/logout",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/plex/webhook/list",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api and /api/v2 allowlist",
                implementation: "generic `api_get`, `api_post`, `api_put`, `api_delete`",
                checks: &[
                    "mcporter confirmed generic error bazarr api_post",
                    "mcporter confirmed generic error bazarr api_put",
                    "mcporter confirmed generic error bazarr api_delete",
                ],
            },
        ],
    },
    ServiceCoverage {
        name: "Tracearr",
        rows: &[
            EndpointCoverage {
                endpoint: "/health",
                implementation: "`service_status`; generic `api_get`; generic `api_post` confirm guard",
                checks: &[
                    "cli status tracearr",
                    "api_get tracearr /health",
                    "api_post blocked tracearr",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v1/public/health",
                implementation: "generic confirmed upstream-error probe through `api_post`",
                checks: &["api_post confirmed upstream error tracearr"],
            },
            EndpointCoverage {
                endpoint: "/api/v1/public/stats",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/v1/public/stats/today",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/v1/public/activity",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/v1/public/streams",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/v1/public/streams/{id}/terminate",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/v1/public/users",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/v1/public/violations",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/v1/public/history",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/v1/debug/sessions",
                implementation: "seeded generic `api_delete` debug-session lifecycle",
                checks: &["mcporter confirmed write tracearr debug sessions delete"],
            },
            EndpointCoverage {
                endpoint: "/api/v1/debug/violations",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/v1/debug/rules",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/v1/debug/library",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/v1/debug/users",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/v1/debug/servers",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/api/v1/debug/reset",
                implementation: "generic passthrough allowlist",
                checks: &[],
            },
            EndpointCoverage {
                endpoint: "/health and /api/v1 allowlist",
                implementation: "generic `api_get`, `api_post`, `api_put`, `api_delete`",
                checks: &[
                    "mcporter confirmed generic error tracearr api_post",
                    "mcporter confirmed generic error tracearr api_put",
                    "mcporter confirmed generic error tracearr api_delete",
                ],
            },
        ],
    },
    ServiceCoverage {
        name: "SABnzbd",
        rows: &[
            EndpointCoverage {
                endpoint: "/api?mode=version&output=json",
                implementation: "`service_status`; generic `api_get`; generic `api_post` confirm guard and confirmed upstream-error probe",
                checks: &[
                    "cli status sabnzbd",
                    "api_get sabnzbd /api?mode=version&output=json",
                    "api_post blocked sabnzbd",
                    "api_post confirmed upstream error sabnzbd",
                ],
            },
            EndpointCoverage {
                endpoint: "/api?mode=queue&output=json",
                implementation: "`download_queue`; generic `api_get`",
                checks: &[
                    "mcporter sabnzbd download_queue",
                    "api_get sabnzbd /api?mode=queue&output=json",
                ],
            },
            EndpointCoverage {
                endpoint: "/api?mode=addurl&name=<url>&output=json",
                implementation: "`download_add`",
                checks: &["mcporter confirmed write sabnzbd download lifecycle"],
            },
            EndpointCoverage {
                endpoint: "/api?mode=queue&name=pause&value=<id>&output=json",
                implementation: "`download_pause` for one job",
                checks: &["mcporter confirmed write sabnzbd download lifecycle"],
            },
            EndpointCoverage {
                endpoint: "/api?mode=pause&output=json",
                implementation: "`download_pause` for all jobs",
                checks: &["mcporter confirmed write sabnzbd download lifecycle"],
            },
            EndpointCoverage {
                endpoint: "/api?mode=queue&name=resume&value=<id>&output=json",
                implementation: "`download_resume` for one job",
                checks: &["mcporter confirmed write sabnzbd download lifecycle"],
            },
            EndpointCoverage {
                endpoint: "/api?mode=resume&output=json",
                implementation: "`download_resume` for all jobs",
                checks: &["mcporter confirmed write sabnzbd download lifecycle"],
            },
            EndpointCoverage {
                endpoint: "/api?mode=queue&name=delete&value=<id>[&del_files=1]&output=json",
                implementation: "`download_remove`",
                checks: &["mcporter confirmed write sabnzbd download lifecycle"],
            },
            EndpointCoverage {
                endpoint: "/api and /api/v2 allowlist",
                implementation: "generic `api_get`, `api_post`, `api_put`, `api_delete`",
                checks: &[
                    "mcporter confirmed generic error sabnzbd api_post",
                    "mcporter confirmed generic error sabnzbd api_put",
                    "mcporter confirmed generic error sabnzbd api_delete",
                ],
            },
        ],
    },
    ServiceCoverage {
        name: "qBittorrent",
        rows: &[
            EndpointCoverage {
                endpoint: "/api/v2/app/version",
                implementation: "`service_status`; generic `api_get`; generic `api_post` confirm guard and confirmed upstream-error probe",
                checks: &[
                    "cli status qbittorrent",
                    "api_get qbittorrent /api/v2/app/version",
                    "api_post blocked qbittorrent",
                    "api_post confirmed upstream error qbittorrent",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v2/torrents/info",
                implementation: "`download_queue`; generic `api_get`",
                checks: &[
                    "mcporter qbittorrent download_queue",
                    "api_get qbittorrent /api/v2/torrents/info",
                ],
            },
            EndpointCoverage {
                endpoint: "/api/v2/torrents/add",
                implementation: "`download_add`",
                checks: &["mcporter confirmed write lifecycle qbittorrent torrent"],
            },
            EndpointCoverage {
                endpoint: "/api/v2/torrents/stop",
                implementation: "`download_pause`",
                checks: &["mcporter confirmed write lifecycle qbittorrent torrent"],
            },
            EndpointCoverage {
                endpoint: "/api/v2/torrents/start",
                implementation: "`download_resume`",
                checks: &["mcporter confirmed write lifecycle qbittorrent torrent"],
            },
            EndpointCoverage {
                endpoint: "/api/v2/torrents/delete",
                implementation: "`download_remove`",
                checks: &["mcporter confirmed write lifecycle qbittorrent torrent"],
            },
            EndpointCoverage {
                endpoint: "/api/v2 allowlist",
                implementation: "generic `api_get`, `api_post`, `api_put`, `api_delete`",
                checks: &[
                    "mcporter confirmed generic error qbittorrent api_post",
                    "mcporter confirmed generic error qbittorrent api_put",
                    "mcporter confirmed generic error qbittorrent api_delete",
                ],
            },
        ],
    },
    ServiceCoverage {
        name: "Plex",
        rows: &[
            EndpointCoverage {
                endpoint: "/identity",
                implementation: "`service_status`; generic `api_get`; generic `api_post` confirm guard and confirmed upstream-error probe",
                checks: &[
                    "cli status plex",
                    "api_get plex /identity",
                    "api_post blocked plex",
                    "api_post confirmed upstream error plex",
                ],
            },
            EndpointCoverage {
                endpoint: "/status/sessions",
                implementation: "`media_sessions`",
                checks: &["mcporter plex media_sessions"],
            },
            EndpointCoverage {
                endpoint: "/library/sections",
                implementation: "`media_libraries`",
                checks: &["mcporter plex media_libraries"],
            },
            EndpointCoverage {
                endpoint: "/library/search?query=...",
                implementation: "`media_search`",
                checks: &["mcporter plex media_search"],
            },
            EndpointCoverage {
                endpoint: "/library/sections/{library}/refresh",
                implementation: "`media_scan`",
                checks: &["mcporter confirmed write plex media_scan"],
            },
            EndpointCoverage {
                endpoint: "/identity, /library, /status, /servers allowlist",
                implementation: "generic `api_get`, `api_post`, `api_put`, `api_delete`",
                checks: &[
                    "mcporter confirmed generic error plex api_post",
                    "mcporter confirmed generic error plex api_put",
                    "mcporter confirmed generic error plex api_delete",
                ],
            },
        ],
    },
    ServiceCoverage {
        name: "Jellyfin",
        rows: &[
            EndpointCoverage {
                endpoint: "/System/Info/Public",
                implementation: "`service_status`; generic `api_get`; generic `api_post` confirm guard and confirmed upstream-error probe",
                checks: &[
                    "cli status jellyfin",
                    "api_get jellyfin /System/Info/Public",
                    "api_post blocked jellyfin",
                    "api_post confirmed upstream error jellyfin",
                ],
            },
            EndpointCoverage {
                endpoint: "/Sessions",
                implementation: "`media_sessions`",
                checks: &["mcporter jellyfin media_sessions"],
            },
            EndpointCoverage {
                endpoint: "/Library/VirtualFolders",
                implementation: "`media_libraries`",
                checks: &["mcporter jellyfin media_libraries"],
            },
            EndpointCoverage {
                endpoint: "/Items?searchTerm=...&includeItemTypes=Movie,Series,Episode&recursive=true",
                implementation: "`media_search`",
                checks: &["mcporter jellyfin media_search"],
            },
            EndpointCoverage {
                endpoint: "/Library/Refresh",
                implementation: "`media_scan`",
                checks: &["mcporter confirmed write jellyfin media_scan"],
            },
            EndpointCoverage {
                endpoint: "/System, /Items, /Users, /Library, /Sessions allowlist",
                implementation: "generic `api_get`, `api_post`, `api_put`, `api_delete`",
                checks: &[
                    "mcporter confirmed generic error jellyfin api_post",
                    "mcporter confirmed generic error jellyfin api_put",
                    "mcporter confirmed generic error jellyfin api_delete",
                ],
            },
        ],
    },
];
