#!/usr/bin/env bash
# SessionStart / ConfigChange hook for the radarr plugin.
#
# Bridges userConfig -> a 600-mode env file the skill scripts source. Claude Code
# injects CLAUDE_PLUGIN_OPTION_* only into plugin subprocesses (this hook), NOT
# into the agent's Bash tool that runs the skill's curl. The userConfig keys are
# named to match the env-var names the skill already uses, so this re-exports
# every CLAUDE_PLUGIN_OPTION_<NAME> as <NAME>. Writes only that file; touches no service.
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lab-radarr"
CONFIG_FILE="${CONFIG_DIR}/config.env"

mkdir -p "$CONFIG_DIR"; chmod 700 "$CONFIG_DIR" 2>/dev/null || true
umask 177
tmp="${CONFIG_FILE}.tmp.$$"
echo "# Generated by the radarr plugin hook. Do not edit by hand." > "$tmp"

count=0
while IFS='=' read -r name value; do
  case "$name" in
    CLAUDE_PLUGIN_OPTION_*) ;;
    *) continue ;;
  esac
  key="${name#CLAUDE_PLUGIN_OPTION_}"
  [ -n "$value" ] || continue
  case "$value" in
    *$'\n'* | *$'\r'*) echo "radarr: ${key} contains a newline; skipping" >&2; continue ;;
  esac
  esc=$(printf '%s' "$value" | sed "s/'/'\\''/g")
  printf "%s='%s'\n" "$key" "$esc" >> "$tmp"
  count=$((count + 1))
done < <(env)

mv "$tmp" "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE" 2>/dev/null || true

if [ "$count" -eq 0 ]; then
  echo "radarr: not configured yet - set the service URL/key in the plugin settings." >&2
else
  echo "radarr: wrote ${count} settings to ${CONFIG_FILE}"
fi
