//! Rust data-table emission.

use std::fmt::Write as _;

use super::{OperationOut, RepresentationOut, TypeOut};

pub(super) fn emit_rust(service: &str, operations: &[OperationOut], types: &[TypeOut]) -> String {
    let supported = operations
        .iter()
        .filter(|operation| operation.omission_reason.is_none())
        .count();
    let omitted = operations.len() - supported;
    let mut output = String::with_capacity(128 * 1024);
    let _ = writeln!(
        output,
        "//! GENERATED by `cargo xtask gen-openapi` from specs/{service}.openapi.* -- DO NOT EDIT.\n//!\n//! {supported} supported operations, {omitted} omitted operations, {} component types.\n#![allow(clippy::all)]\nuse crate::openapi::{{BodyEncoding, HttpMethod, OmittedOperationSpec, OperationSpec, ParameterLocation, ParameterSpec, ParameterStyle, RepresentationSpec, RequestBodySpec, TypeDef}};\n",
        types.len()
    );
    let _ = writeln!(output, "pub static OPERATIONS: &[OperationSpec] = &[");
    for operation in operations
        .iter()
        .filter(|operation| operation.omission_reason.is_none())
    {
        emit_operation(&mut output, operation);
    }
    let _ = writeln!(output, "];\n");

    let _ = writeln!(
        output,
        "pub static OMITTED_OPERATIONS: &[OmittedOperationSpec] = &["
    );
    for operation in operations
        .iter()
        .filter(|operation| operation.omission_reason.is_some())
    {
        let _ = writeln!(
            output,
            "    OmittedOperationSpec {{ name: \"{}\", method: {}, path: \"{}\", reason: \"{}\" }},",
            esc(&operation.name),
            method_variant(&operation.method),
            esc(&operation.path),
            esc(operation.omission_reason.as_deref().unwrap_or_default())
        );
    }
    let _ = writeln!(output, "];\n");

    let _ = writeln!(output, "pub static TYPES: &[TypeDef] = &[");
    for output_type in types {
        let _ = writeln!(
            output,
            "    TypeDef {{ name: \"{}\", ts: \"{}\" }},",
            esc(&output_type.name),
            esc(&output_type.ts)
        );
    }
    let _ = writeln!(output, "];");
    output
}

fn emit_operation(output: &mut String, operation: &OperationOut) {
    let path_params = operation
        .parameters
        .iter()
        .filter(|parameter| parameter.location == "path")
        .map(|parameter| format!("\"{}\"", esc(&parameter.name)))
        .collect::<Vec<_>>()
        .join(", ");
    let query_params = operation
        .parameters
        .iter()
        .filter(|parameter| parameter.location == "query")
        .map(|parameter| format!("\"{}\"", esc(&parameter.name)))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(
        output,
        "    OperationSpec {{ name: \"{}\", method: {}, path: \"{}\", path_params: &[{}], query_params: &[{}], has_body: {}, parameters: &[",
        esc(&operation.name),
        method_variant(&operation.method),
        esc(&operation.path),
        path_params,
        query_params,
        operation.request_body.is_some()
    );
    for parameter in &operation.parameters {
        let _ = writeln!(
            output,
            "        ParameterSpec {{ name: \"{}\", location: {}, required: {}, schema: \"{}\", style: {}, explode: {} }},",
            esc(&parameter.name),
            location_variant(&parameter.location),
            parameter.required,
            esc(&parameter.schema),
            style_variant(&parameter.style),
            parameter.explode
        );
    }
    let _ = write!(output, "    ], request_body: ");
    if let Some(body) = &operation.request_body {
        let _ = write!(
            output,
            "Some(RequestBodySpec {{ required: {}, representations: &[",
            body.required
        );
        for representation in &body.representations {
            emit_representation(output, representation);
        }
        let _ = write!(output, "] }})");
    } else {
        let _ = write!(output, "None");
    }
    let _ = write!(output, ", responses: &[");
    for representation in &operation.responses {
        emit_representation(output, representation);
    }
    let _ = writeln!(
        output,
        "], request_type: {}, response_type: {}, tag: \"{}\", summary: \"{}\" }},",
        opt_str(&operation.request_type),
        opt_str(&operation.response_type),
        esc(&operation.tag),
        esc(&operation.summary)
    );
}

fn emit_representation(output: &mut String, representation: &RepresentationOut) {
    let _ = write!(
        output,
        "RepresentationSpec {{ status: {}, media_type: \"{}\", encoding: {}, schema: \"{}\", encoding_metadata: \"{}\" }},",
        opt_str(&representation.status),
        esc(&representation.media_type),
        encoding_variant(&representation.encoding),
        esc(&representation.schema),
        esc(&representation.encoding_metadata)
    );
}

fn method_variant(method: &str) -> &'static str {
    match method {
        "GET" => "HttpMethod::Get",
        "POST" => "HttpMethod::Post",
        "PUT" => "HttpMethod::Put",
        "DELETE" => "HttpMethod::Delete",
        "PATCH" => "HttpMethod::Patch",
        other => panic!("unsupported generated HTTP method `{other}`"),
    }
}

fn location_variant(location: &str) -> &'static str {
    match location {
        "path" => "ParameterLocation::Path",
        "query" => "ParameterLocation::Query",
        "header" => "ParameterLocation::Header",
        "cookie" => "ParameterLocation::Cookie",
        other => panic!("unsupported generated parameter location `{other}`"),
    }
}

fn style_variant(style: &str) -> &'static str {
    match style {
        "simple" => "ParameterStyle::Simple",
        "label" => "ParameterStyle::Label",
        "matrix" => "ParameterStyle::Matrix",
        "form" => "ParameterStyle::Form",
        "spaceDelimited" => "ParameterStyle::SpaceDelimited",
        "pipeDelimited" => "ParameterStyle::PipeDelimited",
        "deepObject" => "ParameterStyle::DeepObject",
        other => panic!("unsupported generated parameter style `{other}`"),
    }
}

fn encoding_variant(encoding: &str) -> &'static str {
    match encoding {
        "json" => "BodyEncoding::Json",
        "form" => "BodyEncoding::FormUrlEncoded",
        "multipart" => "BodyEncoding::Multipart",
        "text" => "BodyEncoding::Text",
        "binary" => "BodyEncoding::Binary",
        other => panic!("unsupported generated body encoding `{other}`"),
    }
}

fn esc(value: &str) -> String {
    value.chars().fold(String::new(), |mut output, character| {
        match character {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            other => output.push(other),
        }
        output
    })
}

fn opt_str(value: &Option<String>) -> String {
    value
        .as_ref()
        .map(|value| format!("Some(\"{}\")", esc(value)))
        .unwrap_or_else(|| "None".to_string())
}
